### ISSUE TITLE
Timeout on some queries and unable to adjust default timeout setting

### ISSUE THREAD

**Issue by drhythm** [newrelic-experimental/nr-reports#8]
## Description
Some queries, for example, those using `SINCE 1 week ago` have a timeout issue when using the CLI. 

Here's the CLI command I use to generate a report:
```
./nr-reports-cli/bin/nr-reports.sh --debug -p examples -n hello-world.html
```
With a query like the following:
```
FROM Log SELECT count(*) since 1 month ago facet filePath
```

In the `nerdgraph.js` file, I specify the timeout, but that seems to be stuck at 5 _(_see error message below_)_:
```
      timeout: 30,
```

## Error message
```
[Mon, 12 Dec 2022 20:36:09 GMT] engine Created temporary directory report-tXqMwU
[Mon, 12 Dec 2022 20:36:09 GMT] engine Rendering hello-world.html to report-tXqMwU/hello-world.pdf...
[Mon, 12 Dec 2022 20:36:09 GMT] nerdgraph {"query":"query($accountId: Int!,$query: Nrql!,$timeout: Seconds)\n      {\n        actor {\n          account(id: $accountId) {\n            nrql(query: $query, timeout: $timeout) {\n              staticChartUrl(chartType: TABLE, format: PNG, width: 640, height: 480)\n            }\n          }\n        }\n      }\n      ","variables":{"accountId":ACC_ID,"query":"FROM Log SELECT count(*) since 1 month ago facet filePath","timeout":5}}
[Mon, 12 Dec 2022 20:36:14 GMT] nerdgraph {"data":{"actor":{"account":{"nrql":null}}},"errors":[{"extensions":{"errorClass":"TIMEOUT"},"locations":[{"column":13,"line":5}],"message":"NRDB query duration exceeded the set timeout","path":["actor","account","nrql"]}]}
[Mon, 12 Dec 2022 20:36:14 GMT] nerdgraph GraphQL post error for query: {"data":{"actor":{"account":{"nrql":null}}},"errors":[{"extensions":{"errorClass":"TIMEOUT"},"locations":[{"column":13,"line":5}],"message":"NRDB query duration exceeded the set timeout","path":["actor","account","nrql"]}]}
[Mon, 12 Dec 2022 20:36:14 GMT] chart-extension {}
Error: GraphQL post error for query: {"data":{"actor":{"account":{"nrql":null}}},"errors":[{"extensions":{"errorClass":"TIMEOUT"},"locations":[{"column":13,"line":5}],"message":"NRDB query duration exceeded the set timeout","path":["actor","account","nrql"]}]}
    at NerdgraphClient.post (~/nr-reports/nr-reports-core/lib/nerdgraph.js:115:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NerdgraphClient.query (~/nr-reports/nr-reports-core/lib/nerdgraph.js:145:25)
    at async NerdgraphClient.runNrql (~/nr-reports/nr-reports-core/lib/nerdgraph.js:180:21)
    at async ChartExtension.run (~/nr-reports/nr-reports-core/lib/extensions/chart-extension.js:85:18)
[Mon, 12 Dec 2022 20:36:17 GMT] engine Publishing 1 files to channel file...
[Mon, 12 Dec 2022 20:36:17 GMT] engine Channel:
{ type: 'file' }
[Mon, 12 Dec 2022 20:36:17 GMT] engine Files:
[Mon, 12 Dec 2022 20:36:17 GMT] engine report-tXqMwU/hello-world.pdf
[Mon, 12 Dec 2022 20:36:17 GMT] engine Removing temporary directory report-tXqMwU...

```

**Comment by sdewitt-newrelic** [comment]
Hi @drhythm , apologize for the long wait.  You wouldn't change it in the code itself.  It is intended to be changed from the template tag like this:

```nunjucks
{% chart "FROM Transaction SELECT rate(count(*), 1 minute) as 'Requests Per Minute' where appName = 'Billing Service (Sandbox)' SINCE last week UNTIL this week TIMESERIES",
        type="AREA",
        width=1024,
        accountId=9999,
        timeout=30
    %}{% endchart %}
```
Can you try that and let me know if it works for you?

**Comment by sdewitt-newrelic** [comment]
Hi @drhythm closing this one as invalid.  Reopen if you still see the issue.
